[243.237495422] 2018-05-22 21:08:42,561 - INFO - launcher: Starting sanity checks
[247.216463089] 2018-05-22 21:08:42,565 - INFO - launcher: Checking for Python 3.5+
[247.216463089] 2018-05-22 21:08:42,565 - INFO - launcher: Checking console encoding
[247.216463089] 2018-05-22 21:08:42,565 - INFO - launcher: Setting console encoding to UTF-8
[248.190879822] 2018-05-22 21:08:42,566 - INFO - launcher: Ensuring we're in the right environment
[250.187873840] 2018-05-22 21:08:42,568 - INFO - launcher: Adding local bins/ folder to path
[252.227306366] 2018-05-22 21:08:42,570 - INFO - launcher: Required checks passed.
[252.227306366] 2018-05-22 21:08:42,570 - INFO - launcher: Optional checks passed.
[253.248453140] 2018-05-22 21:08:42,571 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[6.4017357826232910] 2018-05-22 21:08:48,719 - WARNING - musicbot.config | In config.py::MainThread(7452), line 112 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[6.4017357826232910] 2018-05-22 21:08:48,719 - INFO - musicbot.config | In config.py::MainThread(7452), line 123 in run_checks: Using i18n: config/i18n/en.json
[6.4318208694458008] 2018-05-22 21:08:48,749 - DEBUG - musicbot.json | In json.py::MainThread(7452), line 8 in __init__: Init JSON obj with config/i18n/en.json
[6.6699800491333008] 2018-05-22 21:08:48,987 - DEBUG - musicbot.bot | In bot.py::MainThread(7452), line 227 in _setup_logging: Set logging level to INFO
[6.6699800491333008] 2018-05-22 21:08:48,987 - INFO - musicbot.bot | In bot.py::MainThread(7452), line 84 in __init__: Starting MusicBot 1.9.7
[6.6709785461425781] 2018-05-22 21:08:48,988 - INFO - musicbot.bot | In bot.py::MainThread(7452), line 90 in __init__: Loaded autoplaylist with 2531 entries
[9.6666800975799561] 2018-05-22 21:08:51,984 - DEBUG - musicbot.bot | In bot.py::MainThread(7452), line 1074 in on_ready: Connection established, ready to go.
[9.6676828861236572] 2018-05-22 21:08:51,985 - DEBUG - musicbot.bot | In bot.py::MainThread(7452), line 339 in _cache_app_info: Caching app info
[9.8318872451782227] 2018-05-22 21:08:52,149 - DEBUG - musicbot.bot | In bot.py::MainThread(7452), line 889 in _scheck_ensure_env: Ensuring data folders exist
[9.8328890800476074] 2018-05-22 21:08:52,150 - DEBUG - musicbot.bot | In bot.py::MainThread(7452), line 905 in _scheck_server_permissions: Checking server permissions
[9.8338315486907959] 2018-05-22 21:08:52,151 - DEBUG - musicbot.bot | In bot.py::MainThread(7452), line 909 in _scheck_autoplaylist: Auditing autoplaylist
[9.8338315486907959] 2018-05-22 21:08:52,151 - DEBUG - musicbot.bot | In bot.py::MainThread(7452), line 913 in _scheck_configs: Validating config
[9.8338315486907959] 2018-05-22 21:08:52,151 - DEBUG - musicbot.config | In config.py::MainThread(7452), line 212 in async_validate: Validating options...
[9.8338315486907959] 2018-05-22 21:08:52,151 - DEBUG - musicbot.bot | In bot.py::MainThread(7452), line 916 in _scheck_configs: Validating permissions config
[9.8338315486907959] 2018-05-22 21:08:52,151 - DEBUG - musicbot.permissions | In permissions.py::MainThread(7452), line 64 in async_validate: Validating permissions...
[9.8338315486907959] 2018-05-22 21:08:52,151 - INFO - musicbot.bot | In bot.py::MainThread(7452), line 1091 in on_ready: Connected: 448215584778485760/Octavia#5134
[9.8348324298858643] 2018-05-22 21:08:52,152 - INFO - musicbot.bot | In bot.py::MainThread(7452), line 1099 in on_ready: Owner:     295620934084329472/TheShadow#0554

[9.8358342647552490] 2018-05-22 21:08:52,153 - INFO - musicbot.bot | In bot.py::MainThread(7452), line 1102 in on_ready: Server List:
[9.8368358612060547] 2018-05-22 21:08:52,154 - INFO - musicbot.bot | In bot.py::MainThread(7452), line 1105 in on_ready:  - Renegade Outlaws int. Server
[9.8378522396087646] 2018-05-22 21:08:52,155 - INFO - musicbot.bot | In bot.py::MainThread(7452), line 1151 in on_ready: Not bound to any text channels
[9.8388364315032959] 2018-05-22 21:08:52,156 - INFO - musicbot.bot | In bot.py::MainThread(7452), line 1177 in on_ready: Not autojoining any voice channels
